/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-07-02 21:00:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import com.academia.util.DbConnection;

public final class acesso_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("com.academia.util.DbConnection");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"pt-br\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Sistema Academia - Acesso</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            background-color: #f4f6f9;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 20px 0;\n");
      out.write("        }\n");
      out.write("        .auth-card {\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 500px;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("        .nav-tabs .nav-link {\n");
      out.write("            color: #495057;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("        .nav-tabs .nav-link.active {\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: #0d6efd;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"card auth-card bg-white p-4\">\n");
      out.write("    \n");
      out.write("    <!-- Painel de Login / Cadastro normal -->\n");
      out.write("    <div id=\"auth-pane\">\n");
      out.write("        <div class=\"text-center mb-4\">\n");
      out.write("            <h3 class=\"fw-bold text-primary\">💪 Academia Fit</h3>\n");
      out.write("            <p class=\"text-muted small\">Gerencie seus treinos e matrículas</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <ul class=\"nav nav-tabs nav-fill mb-4\" id=\"authTabs\" role=\"tablist\">\n");
      out.write("            <li class=\"nav-item\" role=\"presentation\">\n");
      out.write("                <button class=\"nav-link active\" id=\"login-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#login-pane\" type=\"button\" role=\"tab\">Entrar</button>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\" role=\"presentation\">\n");
      out.write("                <button class=\"nav-link\" id=\"register-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#register-pane\" type=\"button\" role=\"tab\">Cadastrar-se</button>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("\n");
      out.write("        <div class=\"tab-content\" id=\"authTabsContent\">\n");
      out.write("            \n");
      out.write("            <!-- Login -->\n");
      out.write("            <div class=\"tab-pane fade show active\" id=\"login-pane\" role=\"tabpanel\">\n");
      out.write("                <div id=\"login-alert\" class=\"alert d-none\" role=\"alert\"></div>\n");
      out.write("                <form id=\"form-login\">\n");
      out.write("                    <div class=\"mb-3\">\n");
      out.write("                        <label for=\"login-email\" class=\"form-label\">E-mail</label>\n");
      out.write("                        <input type=\"email\" class=\"form-control\" id=\"login-email\" name=\"email\" required placeholder=\"seuemail@exemplo.com\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mb-3\">\n");
      out.write("                        <label for=\"login-senha\" class=\"form-label\">Senha</label>\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"login-senha\" name=\"senha\" required placeholder=\"••••••••\">\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"text-end mb-3\">\n");
      out.write("                        <a href=\"#\" class=\"text-decoration-none small\" data-bs-toggle=\"modal\" data-bs-target=\"#modalRecuperar\">Esqueci minha senha</a>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"d-grid mt-4\">\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\" id=\"btn-login\">\n");
      out.write("                            <span class=\"spinner-border spinner-border-sm d-none\" role=\"status\" aria-hidden=\"true\"></span>\n");
      out.write("                            Entrar\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Cadastro -->\n");
      out.write("            <div class=\"tab-pane fade\" id=\"register-pane\" role=\"tabpanel\">\n");
      out.write("                <div id=\"register-alert\" class=\"alert d-none\" role=\"alert\"></div>\n");
      out.write("                <form id=\"form-register\">\n");
      out.write("                    <div class=\"mb-3\">\n");
      out.write("                        <label for=\"reg-nome\" class=\"form-label fw-semibold\">Nome Completo</label>\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"reg-nome\" name=\"nome\" required placeholder=\"João da Silva\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"row mb-3\">\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <label for=\"reg-cpf\" class=\"form-label fw-semibold\">CPF</label>\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"reg-cpf\" name=\"cpf\" required placeholder=\"123.456.789-00\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <label for=\"reg-idade\" class=\"form-label fw-semibold\">Idade</label>\n");
      out.write("                            <input type=\"number\" class=\"form-control\" id=\"reg-idade\" name=\"idade\" required min=\"12\" max=\"120\" placeholder=\"Ex: 25\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mb-3\">\n");
      out.write("                        <label for=\"reg-telefone\" class=\"form-label fw-semibold\">Telefone</label>\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"reg-telefone\" name=\"telefone\" required placeholder=\"(11) 99999-9999\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mb-3\">\n");
      out.write("                        <label for=\"reg-plano\" class=\"form-label fw-semibold\">Escolha seu Plano</label>\n");
      out.write("                        <select class=\"form-select\" id=\"reg-plano\" name=\"idPlano\" required>\n");
      out.write("                            <option value=\"\" selected disabled>Selecione um plano...</option>\n");
      out.write("                            ");

                                Connection connPlano = null;
                                PreparedStatement psPlano = null;
                                ResultSet rsPlano = null;
                                try {
                                    connPlano = DbConnection.getConnection();
                                    String sqlPlano = "SELECT idPlano, nome, preco FROM Plano WHERE status = true ORDER BY nome ASC";
                                    psPlano = connPlano.prepareStatement(sqlPlano);
                                    rsPlano = psPlano.executeQuery();
                                    while (rsPlano.next()) {
                                        int idPlano = rsPlano.getInt("idPlano");
                                        String nomePlano = rsPlano.getString("nome");
                                        double precoPlano = rsPlano.getDouble("preco");
                            
      out.write("\n");
      out.write("                                        <option value=\"");
      out.print( idPlano );
      out.write('"');
      out.write('>');
      out.print( nomePlano );
      out.write(" - R$ ");
      out.print( String.format("%.2f", precoPlano) );
      out.write("</option>\n");
      out.write("                            ");

                                    }
                                } catch (Exception e) {
                                    e.printStackTrace();
                                } finally {
                                    if (rsPlano != null) try { rsPlano.close(); } catch (Exception e) {}
                                    if (psPlano != null) try { psPlano.close(); } catch (Exception e) {}
                                    if (connPlano != null) try { connPlano.close(); } catch (Exception e) {}
                                }
                            
      out.write("\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mb-3\">\n");
      out.write("                        <label for=\"reg-email\" class=\"form-label fw-semibold\">E-mail</label>\n");
      out.write("                        <input type=\"email\" class=\"form-control\" id=\"reg-email\" name=\"email\" required placeholder=\"joao@exemplo.com\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mb-3\">\n");
      out.write("                        <label for=\"reg-senha\" class=\"form-label fw-semibold\">Senha</label>\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"reg-senha\" name=\"senha\" required minlength=\"6\" placeholder=\"Mínimo 6 caracteres\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"d-grid mt-4\">\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-success\" id=\"btn-register\">\n");
      out.write("                            <span class=\"spinner-border spinner-border-sm d-none\" role=\"status\" aria-hidden=\"true\"></span>\n");
      out.write("                            Criar Conta\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Painel de Redefinição de Senha (mostrado apenas se houver token na URL) -->\n");
      out.write("    <div id=\"redefinir-pane\" class=\"d-none\">\n");
      out.write("        <div class=\"text-center mb-4\">\n");
      out.write("            <h3 class=\"fw-bold text-primary\">🔒 Nova Senha</h3>\n");
      out.write("            <p class=\"text-muted small\">Crie uma nova senha para sua conta</p>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"redefinir-alert\" class=\"alert d-none\" role=\"alert\"></div>\n");
      out.write("        <form id=\"form-redefinir\">\n");
      out.write("            <input type=\"hidden\" id=\"redefinir-token\">\n");
      out.write("            <div class=\"mb-3\">\n");
      out.write("                <label for=\"redefinir-nova-senha\" class=\"form-label\">Nova Senha</label>\n");
      out.write("                <input type=\"password\" class=\"form-control\" id=\"redefinir-nova-senha\" required placeholder=\"Mínimo 6 caracteres\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"mb-3\">\n");
      out.write("                <label for=\"redefinir-confirma-senha\" class=\"form-label\">Confirmar Nova Senha</label>\n");
      out.write("                <input type=\"password\" class=\"form-control\" id=\"redefinir-confirma-senha\" required placeholder=\"Confirme a nova senha\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"d-grid mt-4\">\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\" id=\"btn-redefinir\">\n");
      out.write("                    <span class=\"spinner-border spinner-border-sm d-none\" role=\"status\" aria-hidden=\"true\"></span>\n");
      out.write("                    Salvar Nova Senha\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"text-center mt-3\">\n");
      out.write("                <a href=\"acesso.jsp\" class=\"text-decoration-none small\">Voltar para o Login</a>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- Modal de Recuperação de Senha -->\n");
      out.write("<div class=\"modal fade\" id=\"modalRecuperar\" tabindex=\"-1\" aria-labelledby=\"modalRecuperarLabel\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <h5 class=\"modal-title fw-bold\" id=\"modalRecuperarLabel\">Recuperar Senha</h5>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Fechar\"></button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("                <div id=\"recuperar-alert\" class=\"alert d-none\" role=\"alert\"></div>\n");
      out.write("                <form id=\"form-recuperar\">\n");
      out.write("                    <p class=\"text-muted small\">Digite seu e-mail cadastrado e enviaremos um link para você redefinir sua senha.</p>\n");
      out.write("                    <div class=\"mb-3\">\n");
      out.write("                        <label for=\"rec-email\" class=\"form-label\">E-mail</label>\n");
      out.write("                        <input type=\"email\" class=\"form-control\" id=\"rec-email\" required placeholder=\"seuemail@exemplo.com\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"d-grid mt-4\">\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\" id=\"btn-recuperar\">\n");
      out.write("                            <span class=\"spinner-border spinner-border-sm d-none\" role=\"status\" aria-hidden=\"true\"></span>\n");
      out.write("                            Enviar Link\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("$(document).ready(function() {\n");
      out.write("\n");
      out.write("    // --- VERIFICA PARÂMETROS NA URL ---\n");
      out.write("    const urlParams = new URLSearchParams(window.location.search);\n");
      out.write("    \n");
      out.write("    if (urlParams.has('ativado')) {\n");
      out.write("        $('#login-alert').addClass('alert-success').text('Sua conta foi ativada com sucesso! Faça login abaixo.').removeClass('d-none');\n");
      out.write("    } else if (urlParams.has('erroAtivacao')) {\n");
      out.write("        const erro = urlParams.get('erroAtivacao');\n");
      out.write("        let msg = 'Erro ao ativar a conta.';\n");
      out.write("        if (erro === 'invalido') msg = 'Token de ativação inválido.';\n");
      out.write("        else if (erro === 'nao_encontrado') msg = 'Link de ativação expirado ou já utilizado.';\n");
      out.write("        else if (erro === 'db_erro' || erro === 'banco') msg = 'Erro interno do servidor ao ativar.';\n");
      out.write("        $('#login-alert').addClass('alert-danger').text(msg).removeClass('d-none');\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    const tokenParam = urlParams.get('token');\n");
      out.write("    if (tokenParam) {\n");
      out.write("        $('#auth-pane').addClass('d-none');\n");
      out.write("        $('#redefinir-pane').removeClass('d-none');\n");
      out.write("        $('#redefinir-token').val(tokenParam);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // --- AJAX DO LOGIN ---\n");
      out.write("    $('#form-login').on('submit', function(e) {\n");
      out.write("        e.preventDefault();\n");
      out.write("        \n");
      out.write("        let alertBox = $('#login-alert');\n");
      out.write("        let btn = $('#btn-login');\n");
      out.write("        let spinner = btn.find('.spinner-border');\n");
      out.write("\n");
      out.write("        alertBox.addClass('d-none').removeClass('alert-success alert-danger');\n");
      out.write("        btn.prop('disabled', true);\n");
      out.write("        spinner.removeClass('d-none');\n");
      out.write("\n");
      out.write("        let formData = {\n");
      out.write("            email: $('#login-email').val(),\n");
      out.write("            senha: $('#login-senha').val()\n");
      out.write("        };\n");
      out.write("\n");
      out.write("        $.ajax({\n");
      out.write("            url: 'api/login',\n");
      out.write("            type: 'POST',\n");
      out.write("            contentType: 'application/json',\n");
      out.write("            data: JSON.stringify(formData),\n");
      out.write("            dataType: 'json',\n");
      out.write("            success: function(response) {\n");
      out.write("                if (response.sucesso) {\n");
      out.write("                    alertBox.addClass('alert-success').text(response.mensagem || 'Login efetuado com sucesso! Redirecionando...').removeClass('d-none');\n");
      out.write("                    setTimeout(function() {\n");
      out.write("                        let urlDestino = 'index.jsp';\n");
      out.write("                        if (response.role === 'ALUNO') urlDestino = 'aluno.jsp';\n");
      out.write("                        else if (response.role === 'FUNCIONARIO') urlDestino = 'funcionario.jsp';\n");
      out.write("                        else if (response.role === 'GERENTE') urlDestino = 'gerente.jsp';\n");
      out.write("                        window.location.href = urlDestino;\n");
      out.write("                    }, 1500);\n");
      out.write("                } else {\n");
      out.write("                    alertBox.addClass('alert-danger').text(response.mensagem || 'Credenciais inválidas.').removeClass('d-none');\n");
      out.write("                    btn.prop('disabled', false);\n");
      out.write("                    spinner.addClass('d-none');\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("            error: function(xhr) {\n");
      out.write("                let msg = 'Erro ao comunicar com o servidor.';\n");
      out.write("                if (xhr.responseJSON && xhr.responseJSON.mensagem) {\n");
      out.write("                    msg = xhr.responseJSON.mensagem;\n");
      out.write("                }\n");
      out.write("                alertBox.addClass('alert-danger').text(msg).removeClass('d-none');\n");
      out.write("                btn.prop('disabled', false);\n");
      out.write("                spinner.addClass('d-none');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    // --- AJAX DO REGISTRO ---\n");
      out.write("    $('#form-register').on('submit', function(e) {\n");
      out.write("        e.preventDefault();\n");
      out.write("        \n");
      out.write("        let alertBox = $('#register-alert');\n");
      out.write("        let btn = $('#btn-register');\n");
      out.write("        let spinner = btn.find('.spinner-border');\n");
      out.write("\n");
      out.write("        alertBox.addClass('d-none').removeClass('alert-success alert-danger');\n");
      out.write("        btn.prop('disabled', true);\n");
      out.write("        spinner.removeClass('d-none');\n");
      out.write("\n");
      out.write("        let formData = {\n");
      out.write("            nome: $('#reg-nome').val(),\n");
      out.write("            email: $('#reg-email').val(),\n");
      out.write("            senha: $('#reg-senha').val(),\n");
      out.write("            cpf: $('#reg-cpf').val(),\n");
      out.write("            idade: parseInt($('#reg-idade').val()),\n");
      out.write("            telefone: $('#reg-telefone').val(),\n");
      out.write("            idPlano: parseInt($('#reg-plano').val()),\n");
      out.write("            role: 'ALUNO'\n");
      out.write("        };\n");
      out.write("\n");
      out.write("        $.ajax({\n");
      out.write("            url: 'api/cadastro',\n");
      out.write("            type: 'POST',\n");
      out.write("            contentType: 'application/json',\n");
      out.write("            data: JSON.stringify(formData),\n");
      out.write("            dataType: 'json',\n");
      out.write("            success: function(response) {\n");
      out.write("                if (response.sucesso) {\n");
      out.write("                    alertBox.addClass('alert-success').text(response.mensagem).removeClass('d-none');\n");
      out.write("                    $('#form-register')[0].reset();\n");
      out.write("                    btn.prop('disabled', false);\n");
      out.write("                    spinner.addClass('d-none');\n");
      out.write("                } else {\n");
      out.write("                    alertBox.addClass('alert-danger').text(response.mensagem || 'Erro ao registrar usuário.').removeClass('d-none');\n");
      out.write("                    btn.prop('disabled', false);\n");
      out.write("                    spinner.addClass('d-none');\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("            error: function(xhr) {\n");
      out.write("                let msg = 'Erro técnico ao processar requisição.';\n");
      out.write("                if (xhr.responseJSON && xhr.responseJSON.mensagem) {\n");
      out.write("                    msg = xhr.responseJSON.mensagem;\n");
      out.write("                }\n");
      out.write("                alertBox.addClass('alert-danger').text(msg).removeClass('d-none');\n");
      out.write("                btn.prop('disabled', false);\n");
      out.write("                spinner.addClass('d-none');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    // --- AJAX DE SOLICITAR RECUPERAÇÃO ---\n");
      out.write("    $('#form-recuperar').on('submit', function(e) {\n");
      out.write("        e.preventDefault();\n");
      out.write("        let alertBox = $('#recuperar-alert');\n");
      out.write("        let btn = $('#btn-recuperar');\n");
      out.write("        let spinner = btn.find('.spinner-border');\n");
      out.write("\n");
      out.write("        alertBox.addClass('d-none').removeClass('alert-success alert-danger');\n");
      out.write("        btn.prop('disabled', true);\n");
      out.write("        spinner.removeClass('d-none');\n");
      out.write("\n");
      out.write("        let email = $('#rec-email').val();\n");
      out.write("\n");
      out.write("        $.ajax({\n");
      out.write("            url: 'api/recuperar-senha',\n");
      out.write("            type: 'POST',\n");
      out.write("            contentType: 'application/json',\n");
      out.write("            data: JSON.stringify({ email: email }),\n");
      out.write("            dataType: 'json',\n");
      out.write("            success: function(response) {\n");
      out.write("                alertBox.addClass('alert-success').text(response.mensagem).removeClass('d-none');\n");
      out.write("                $('#form-recuperar')[0].reset();\n");
      out.write("                btn.prop('disabled', false);\n");
      out.write("                spinner.addClass('d-none');\n");
      out.write("            },\n");
      out.write("            error: function(xhr) {\n");
      out.write("                let msg = 'Erro ao solicitar recuperação.';\n");
      out.write("                if (xhr.responseJSON && xhr.responseJSON.mensagem) {\n");
      out.write("                    msg = xhr.responseJSON.mensagem;\n");
      out.write("                }\n");
      out.write("                alertBox.addClass('alert-danger').text(msg).removeClass('d-none');\n");
      out.write("                btn.prop('disabled', false);\n");
      out.write("                spinner.addClass('d-none');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    // --- AJAX DE REDEFINIR SENHA ---\n");
      out.write("    $('#form-redefinir').on('submit', function(e) {\n");
      out.write("        e.preventDefault();\n");
      out.write("        \n");
      out.write("        let alertBox = $('#redefinir-alert');\n");
      out.write("        let btn = $('#btn-redefinir');\n");
      out.write("        let spinner = btn.find('.spinner-border');\n");
      out.write("        \n");
      out.write("        let token = $('#redefinir-token').val();\n");
      out.write("        let novaSenha = $('#redefinir-nova-senha').val();\n");
      out.write("        let confirmaSenha = $('#redefinir-confirma-senha').val();\n");
      out.write("\n");
      out.write("        if (novaSenha !== confirmaSenha) {\n");
      out.write("            alertBox.addClass('alert-danger').text('As senhas não coincidem.').removeClass('d-none');\n");
      out.write("            return;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        alertBox.addClass('d-none').removeClass('alert-success alert-danger');\n");
      out.write("        btn.prop('disabled', true);\n");
      out.write("        spinner.removeClass('d-none');\n");
      out.write("\n");
      out.write("        $.ajax({\n");
      out.write("            url: 'api/recuperar-senha',\n");
      out.write("            type: 'PUT',\n");
      out.write("            contentType: 'application/json',\n");
      out.write("            data: JSON.stringify({\n");
      out.write("                token: token,\n");
      out.write("                novaSenha: novaSenha\n");
      out.write("            }),\n");
      out.write("            dataType: 'json',\n");
      out.write("            success: function(response) {\n");
      out.write("                alertBox.addClass('alert-success').text(response.mensagem + ' Redirecionando para o login...').removeClass('d-none');\n");
      out.write("                setTimeout(function() {\n");
      out.write("                    window.location.href = 'acesso.jsp';\n");
      out.write("                }, 2000);\n");
      out.write("            },\n");
      out.write("            error: function(xhr) {\n");
      out.write("                let msg = 'Erro ao redefinir a senha.';\n");
      out.write("                if (xhr.responseJSON && xhr.responseJSON.mensagem) {\n");
      out.write("                    msg = xhr.responseJSON.mensagem;\n");
      out.write("                }\n");
      out.write("                alertBox.addClass('alert-danger').text(msg).removeClass('d-none');\n");
      out.write("                btn.prop('disabled', false);\n");
      out.write("                spinner.addClass('d-none');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
