/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-07-02 21:01:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.academia.model.Usuario;
import com.academia.model.Aluno;
import com.academia.model.Treino;
import com.academia.dao.AlunoDAO;
import com.academia.dao.TreinoDAO;
import com.academia.dao.CheckInDAO;
import java.sql.Timestamp;
import java.util.List;

public final class aluno_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(11);
    _jspx_imports_classes.add("com.academia.model.Usuario");
    _jspx_imports_classes.add("com.academia.model.Aluno");
    _jspx_imports_classes.add("com.academia.model.Treino");
    _jspx_imports_classes.add("com.academia.dao.AlunoDAO");
    _jspx_imports_classes.add("com.academia.dao.TreinoDAO");
    _jspx_imports_classes.add("com.academia.dao.CheckInDAO");
    _jspx_imports_classes.add("java.sql.Timestamp");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    // Garante que o usuário está logado e possui perfil apropriado
    Usuario usuarioLogado = (Usuario) session.getAttribute("usuarioLogado");
    if (usuarioLogado == null) {
        response.sendRedirect("acesso.jsp");
        return;
    }

    Aluno alunoLogado = null;
    Treino treinoLogado = null;
    List<Timestamp> checkins = null;
    
    AlunoDAO alunoDAO = new AlunoDAO();
    TreinoDAO treinoDAO = new TreinoDAO();
    CheckInDAO checkInDAO = new CheckInDAO();
    try {
        alunoLogado = alunoDAO.buscarPorIdUsuario(usuarioLogado.getIdUsuario());
        if (alunoLogado != null) {
            treinoLogado = treinoDAO.buscarPorAluno(alunoLogado.getIdAluno());
            checkins = checkInDAO.listarDatasPorAluno(alunoLogado.getIdAluno());
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"pt-br\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Área do Aluno - Academia Fit</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        .custom-card {\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            box-shadow: 0 4px 10px rgba(0,0,0,0.05);\n");
      out.write("        }\n");
      out.write("        .exercise-item {\n");
      out.write("            border-left: 4px solid #ffc107;\n");
      out.write("            background-color: #f8f9fa;\n");
      out.write("            transition: all 0.2s;\n");
      out.write("        }\n");
      out.write("        .exercise-item:hover {\n");
      out.write("            background-color: #f1f3f5;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-light\">\n");
      out.write("\n");
      out.write("    <nav class=\"navbar navbar-dark bg-primary mb-4 shadow-sm\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <span class=\"navbar-brand mb-0 h1 fw-bold text-warning\">\n");
      out.write("                <i class=\"fas fa-chart-line me-2\"></i> Evolução e Relatórios\n");
      out.write("            </span>\n");
      out.write("            <div>\n");
      out.write("                <a href=\"relatorio-aluno.jsp\" class=\"btn btn-sm btn-outline-light me-2\">Ver Relatorio</a>\n");
      out.write("                ");
 if (alunoLogado != null) { 
      out.write("\n");
      out.write("                    <button class=\"btn btn-sm btn-outline-light me-2\" data-bs-toggle=\"modal\" data-bs-target=\"#modalPerfil\">\n");
      out.write("                        <i class=\"fas fa-user-cog me-1\"></i> Meus Dados\n");
      out.write("                    </button>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                <span class=\"text-white small me-3\">Olá, ");
      out.print( (alunoLogado != null) ? alunoLogado.getNome() : usuarioLogado.getEmailLogin() );
      out.write("</span>\n");
      out.write("                <a href=\"api/logout\" class=\"btn btn-sm btn-danger\"><i class=\"fas fa-sign-out-alt me-1\"></i> Sair</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div class=\"container mb-5\">\n");
      out.write("        \n");
      out.write("        <div id=\"alert-aluno\" class=\"alert d-none\" role=\"alert\"></div>\n");
      out.write("\n");
      out.write("        ");
 if (alunoLogado == null) { 
      out.write("\n");
      out.write("            <!-- Caso a conta do Usuário não esteja vinculada a nenhum Aluno -->\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-12\">\n");
      out.write("                    <div class=\"card custom-card p-5 bg-white text-center shadow-sm\">\n");
      out.write("                        <i class=\"fas fa-exclamation-circle text-danger fs-1 mb-3\"></i>\n");
      out.write("                        <h3 class=\"fw-bold\">ALUNO SEM TREINO ENCONTRADO</h3>\n");
      out.write("                        <p class=\"text-muted\">A sua conta de acesso (<strong>");
      out.print( usuarioLogado.getEmailLogin() );
      out.write("</strong>) ainda não foi vinculada a nenhum treino.</p>\n");
      out.write("                        <p class=\"text-muted\">Por favor, direcione-se a um professor para que ele possa orientá-lo(a).</p>\n");
      out.write("                        <a href=\"api/logout\" class=\"btn btn-danger mt-3 px-4\"><i class=\"fas fa-sign-out-alt me-2\"></i> Efetuar Logout</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        ");
 } else if (alunoLogado.getMatricula() == null || !alunoLogado.getMatricula().isStatus()) { 
      out.write("\n");
      out.write("            <!-- Caso o Aluno tenha cadastro mas matrícula esteja inativa -->\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-12\">\n");
      out.write("                    <div class=\"card custom-card p-5 bg-white text-center shadow-sm\">\n");
      out.write("                        <i class=\"fas fa-hand-holding-usd text-warning fs-1 mb-3\"></i>\n");
      out.write("                        <h3 class=\"fw-bold\">Matrícula Inativa</h3>\n");
      out.write("                        <p class=\"text-muted\">Olá, <strong>");
      out.print( alunoLogado.getNome() );
      out.write("</strong>. Consta no sistema que a sua matrícula ou plano está inativo no momento.</p>\n");
      out.write("                        <p class=\"text-muted\">Por favor, procure a recepção para regularizar sua matrícula e liberar seu acesso aos treinos e check-ins.</p>\n");
      out.write("                        <a href=\"api/logout\" class=\"btn btn-danger mt-3 px-4\"><i class=\"fas fa-sign-out-alt me-2\"></i> Efetuar Logout</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("            <!-- Caso de matrícula ativa normal -->\n");
      out.write("            ");
 if (treinoLogado != null) { 
      out.write("\n");
      out.write("                <div class=\"card custom-card bg-dark text-white p-4 mb-4 text-center\">\n");
      out.write("                    <h4 class=\"fw-bold text-warning mb-2\">Vai treinar hoje? 🏋️‍♂️</h4>\n");
      out.write("                    <p class=\"text-muted small mb-3\">Selecione o treino do dia e clique no botão para registrar a sua presença.</p>\n");
      out.write("                    \n");
      out.write("                    <form id=\"form-checkin\" class=\"d-flex flex-column flex-sm-row justify-content-center align-items-center gap-2 max-width-500 mx-auto\">\n");
      out.write("                        <select class=\"form-select w-auto\" id=\"checkin-treino\" name=\"treino_bloco\" required>\n");
      out.write("                            <option value=\"\" selected disabled>Escolha o treino...</option>\n");
      out.write("                            <option value=\"A\">Treino A (Geral)</option>\n");
      out.write("                        </select>\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-warning fw-bold px-4 w-100 w-sm-auto\" id=\"btn-checkin\">\n");
      out.write("                            <i class=\"fas fa-calendar-check me-2\"></i> Fazer Check-In\n");
      out.write("                        </button>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"row g-4\">\n");
      out.write("                \n");
      out.write("                <!-- Ficha de Exercícios -->\n");
      out.write("                <div class=\"col-lg-7\">\n");
      out.write("                    ");
 if (treinoLogado == null) { 
      out.write("\n");
      out.write("                        <div class=\"card custom-card p-5 bg-white h-100 text-center d-flex flex-column justify-content-center align-items-center shadow-sm\">\n");
      out.write("                            <i class=\"fas fa-exclamation-triangle text-warning fs-1 mb-3\"></i>\n");
      out.write("                            <h4 class=\"fw-bold text-dark\">Nenhum treino cadastrado</h4>\n");
      out.write("                            <p class=\"text-muted small\">Você ainda não possui uma ficha de exercícios cadastrada no sistema.</p>\n");
      out.write("                            <p class=\"text-muted small\">Por favor, solicite a criação de um treino personalizado diretamente ao seu professor ou instrutor físico.</p>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } else { 
      out.write("\n");
      out.write("                        <div class=\"card custom-card p-4 bg-white h-100\">\n");
      out.write("                            <div class=\"d-flex align-items-center mb-3\">\n");
      out.write("                                <i class=\"fas fa-dumbbell text-primary fs-4 me-2\"></i>\n");
      out.write("                                <h5 class=\"fw-bold mb-0\">Minha Ficha de Exercícios</h5>\n");
      out.write("                            </div>\n");
      out.write("                            \n");
      out.write("                            <div class=\"mb-3 p-3 bg-light rounded border-start border-primary border-4\">\n");
      out.write("                                <div class=\"small text-muted\">Professor Responsável</div>\n");
      out.write("                                <div class=\"fw-bold text-dark\">\n");
      out.write("								    ");
      out.print( (treinoLogado.getProfessor() != null) ? treinoLogado.getProfessor().getNome() : "Professor não atribuído" );
      out.write("\n");
      out.write("								</div>\n");
      out.write("                                <div class=\"small text-muted mt-2\">Período de Validade</div>\n");
      out.write("								<div class=\"fw-medium text-secondary\">\n");
      out.write("								    ");
 
								        if (treinoLogado != null && treinoLogado.getDataInicio() != null && treinoLogado.getDataFim() != null) {
								            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
								    
      out.write("\n");
      out.write("								            ");
      out.print( sdf.format(treinoLogado.getDataInicio()) );
      out.write(" até \n");
      out.write("								            ");
      out.print( sdf.format(treinoLogado.getDataFim()) );
      out.write("\n");
      out.write("								    ");
 
								        } else {
								    
      out.write("\n");
      out.write("								            Data não disponível\n");
      out.write("								    ");
 
								        }
								    
      out.write("\n");
      out.write("								</div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"mt-4\">\n");
      out.write("                                <h6 class=\"fw-bold mb-2\"><i class=\"fas fa-clipboard-list me-1 text-primary\"></i> Exercícios e Instruções:</h6>\n");
      out.write("                                <div class=\"p-3 bg-light rounded text-dark\" style=\"white-space: pre-line; line-height: 1.6;\">\n");
      out.write("                                    ");
      out.print( treinoLogado.getDescricao() );
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Histórico de Presença -->\n");
      out.write("                <div class=\"col-lg-5\">\n");
      out.write("                    <div class=\"card custom-card p-4 bg-white h-100\">\n");
      out.write("                        <div class=\"d-flex align-items-center mb-3\">\n");
      out.write("                            <i class=\"fas fa-history text-success fs-4 me-2\"></i>\n");
      out.write("                            <h5 class=\"fw-bold mb-0\">Histórico de Presença</h5>\n");
      out.write("                        </div>\n");
      out.write("                        <p class=\"text-muted small\">Últimos treinos concluídos salvos no sistema.</p>\n");
      out.write("\n");
      out.write("                        <div class=\"table-responsive\">\n");
      out.write("                            <table class=\"table table-sm table-borderless align-middle\">\n");
      out.write("                                <thead>\n");
      out.write("                                    <tr class=\"border-bottom text-muted small\">\n");
      out.write("                                        <th>Treino</th>\n");
      out.write("                                        <th class=\"text-end\">Data / Hora</th>\n");
      out.write("                                    </tr>\n");
      out.write("                                </thead>\n");
      out.write("                                <tbody id=\"historico-checkin\">\n");
      out.write("                                    ");
 if (checkins != null && !checkins.isEmpty()) { 
      out.write("\n");
      out.write("                                        ");
 for (Timestamp ts : checkins) { 
      out.write("\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td><span class=\"badge bg-success\">Check-in Realizado</span></td>\n");
      out.write("                                                <td class=\"text-end text-muted small\">");
      out.print( new java.text.SimpleDateFormat("dd/MM/yyyy - HH:mm").format(ts) );
      out.write("</td>\n");
      out.write("                                            </tr>\n");
      out.write("                                        ");
 } 
      out.write("\n");
      out.write("                                    ");
 } else { 
      out.write("\n");
      out.write("                                        <tr>\n");
      out.write("                                            <td colspan=\"2\" class=\"text-center text-muted small py-3\">Nenhum check-in registrado ainda.</td>\n");
      out.write("                                        </tr>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                </tbody>\n");
      out.write("                            </table>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("    $(document).ready(function() {\n");
      out.write("\n");
      out.write("        // --- AJAX: DISPARAR CHECK-IN DO DIA ---\n");
      out.write("        $('#form-checkin').on('submit', function(e) {\n");
      out.write("            e.preventDefault();\n");
      out.write("\n");
      out.write("            let btn = $('#btn-checkin');\n");
      out.write("            let alertBox = $('#alert-aluno');\n");
      out.write("\n");
      out.write("            btn.prop('disabled', true);\n");
      out.write("            alertBox.addClass('d-none').removeClass('alert-success alert-danger');\n");
      out.write("\n");
      out.write("            let idTreino = ");
      out.print( (treinoLogado != null) ? treinoLogado.getIdTreino() : "null" );
      out.write(";\n");
      out.write("            $.ajax({\n");
      out.write("                url: 'api/checkin',\n");
      out.write("                type: 'POST',\n");
      out.write("                contentType: 'application/json',\n");
      out.write("                data: JSON.stringify({\n");
      out.write("                    idAcademia: 1,\n");
      out.write("                    idTreino: idTreino\n");
      out.write("                }),\n");
      out.write("                dataType: 'json',\n");
      out.write("                success: function(response) {\n");
      out.write("                    if (response.sucesso) {\n");
      out.write("                        alertBox.removeClass('d-none').addClass('alert-success').text(response.mensagem || 'Check-in realizado com sucesso!');\n");
      out.write("                        \n");
      out.write("                        let agora = new Date();\n");
      out.write("                        let dataFormatada = agora.toLocaleDateString('pt-BR') + ' - ' + agora.toLocaleTimeString('pt-BR', {hour: '2-digit', minute:'2-digit'});\n");
      out.write("                        \n");
      out.write("                        let novaLinha = '<tr>' +\n");
      out.write("                            '<td><span class=\"badge bg-success\">Check-in Realizado</span></td>' +\n");
      out.write("                            '<td class=\"text-end text-muted small\">' + dataFormatada + '</td>' +\n");
      out.write("                            '</tr>';\n");
      out.write("                        \n");
      out.write("                        // Remove a linha de \"Nenhum check-in registrado ainda\"\n");
      out.write("                        $('#historico-checkin').find('.text-center').closest('tr').remove();\n");
      out.write("                        $('#historico-checkin').prepend(novaLinha);\n");
      out.write("                    } else {\n");
      out.write("                        alertBox.removeClass('d-none').addClass('alert-danger').text(response.mensagem || 'Erro ao realizar check-in.');\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                error: function(xhr) {\n");
      out.write("                    let msg = 'Erro técnico de comunicação ao enviar check-in.';\n");
      out.write("                    if (xhr.responseJSON && xhr.responseJSON.mensagem) {\n");
      out.write("                        msg = xhr.responseJSON.mensagem;\n");
      out.write("                    }\n");
      out.write("                    alertBox.removeClass('d-none').addClass('alert-danger').text(msg);\n");
      out.write("                },\n");
      out.write("                complete: function() {\n");
      out.write("                    btn.prop('disabled', false);\n");
      out.write("                    $('#form-checkin')[0].reset();\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        // --- AJAX: ATUALIZAR PERFIL DO USUÁRIO ---\n");
      out.write("        $('#form-perfil').on('submit', function(e) {\n");
      out.write("            e.preventDefault();\n");
      out.write("            \n");
      out.write("            let btn = $('#btn-salvar-perfil');\n");
      out.write("            let spinner = btn.find('.spinner-border');\n");
      out.write("            let alertBox = $('#perfil-alert');\n");
      out.write("\n");
      out.write("            alertBox.addClass('d-none').removeClass('alert-success alert-danger');\n");
      out.write("            btn.prop('disabled', true);\n");
      out.write("            spinner.removeClass('d-none');\n");
      out.write("\n");
      out.write("            let formData = {\n");
      out.write("                nome: $('#perf-nome').val(),\n");
      out.write("                idade: parseInt($('#perf-idade').val()),\n");
      out.write("                telefone: $('#perf-telefone').val(),\n");
      out.write("                email: $('#perf-email').val()\n");
      out.write("            };\n");
      out.write("\n");
      out.write("            $.ajax({\n");
      out.write("                url: 'api/atualizar-perfil',\n");
      out.write("                type: 'POST',\n");
      out.write("                contentType: 'application/json',\n");
      out.write("                data: JSON.stringify(formData),\n");
      out.write("                dataType: 'json',\n");
      out.write("                success: function(response) {\n");
      out.write("                    if (response.sucesso) {\n");
      out.write("                        alertBox.removeClass('d-none').addClass('alert-success').text(response.mensagem);\n");
      out.write("                        setTimeout(function() {\n");
      out.write("                            location.reload();\n");
      out.write("                        }, 1200);\n");
      out.write("                    } else {\n");
      out.write("                        alertBox.removeClass('d-none').addClass('alert-danger').text(response.mensagem || 'Erro ao atualizar dados.');\n");
      out.write("                        btn.prop('disabled', false);\n");
      out.write("                        spinner.addClass('d-none');\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                error: function(xhr) {\n");
      out.write("                    let msg = 'Erro ao processar alteração de perfil.';\n");
      out.write("                    if (xhr.responseJSON && xhr.responseJSON.mensagem) {\n");
      out.write("                        msg = xhr.responseJSON.mensagem;\n");
      out.write("                    }\n");
      out.write("                    alertBox.removeClass('d-none').addClass('alert-danger').text(msg);\n");
      out.write("                    btn.prop('disabled', false);\n");
      out.write("                    spinner.addClass('d-none');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("\n");
      out.write("    });\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("    <!-- Modal Perfil Aluno -->\n");
      out.write("    ");
 if (alunoLogado != null) { 
      out.write("\n");
      out.write("    <div class=\"modal fade\" id=\"modalPerfil\" tabindex=\"-1\" aria-labelledby=\"modalPerfilLabel\" aria-hidden=\"true\">\n");
      out.write("        <div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("                    <h5 class=\"modal-title fw-bold\" id=\"modalPerfilLabel\"><i class=\"fas fa-user-cog me-2\"></i> Meus Dados</h5>\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Fechar\"></button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-body\">\n");
      out.write("                    <div id=\"perfil-alert\" class=\"alert d-none\" role=\"alert\"></div>\n");
      out.write("                    <form id=\"form-perfil\">\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label for=\"perf-nome\" class=\"form-label fw-semibold\">Nome Completo</label>\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"perf-nome\" required value=\"");
      out.print( alunoLogado.getNome() );
      out.write("\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"row mb-3\">\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"perf-cpf\" class=\"form-label fw-semibold\">CPF (não alterável)</label>\n");
      out.write("                                <input type=\"text\" class=\"form-control bg-light\" id=\"perf-cpf\" value=\"");
      out.print( alunoLogado.getCpf() );
      out.write("\" readonly>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"perf-idade\" class=\"form-label fw-semibold\">Idade</label>\n");
      out.write("                                <input type=\"number\" class=\"form-control\" id=\"perf-idade\" required value=\"");
      out.print( alunoLogado.getIdade() );
      out.write("\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label for=\"perf-telefone\" class=\"form-label fw-semibold\">Telefone</label>\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"perf-telefone\" required value=\"");
      out.print( alunoLogado.getTelefone() );
      out.write("\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label for=\"perf-email\" class=\"form-label fw-semibold\">E-mail</label>\n");
      out.write("                            <input type=\"email\" class=\"form-control\" id=\"perf-email\" required value=\"");
      out.print( usuarioLogado.getEmailLogin() );
      out.write("\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"d-grid mt-4\">\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-primary\" id=\"btn-salvar-perfil\">\n");
      out.write("                                <span class=\"spinner-border spinner-border-sm d-none\" role=\"status\" aria-hidden=\"true\"></span>\n");
      out.write("                                Salvar Alterações\n");
      out.write("                            </button>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
