/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-07-02 21:05:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.academia.model.Usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import com.academia.util.DbConnection;

public final class funcionario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("com.academia.model.Usuario");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("com.academia.util.DbConnection");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    // Garante que apenas usuários logados com perfil FUNCIONARIO ou GERENTE possam acessar
    Usuario usuarioLogado = (Usuario) session.getAttribute("usuarioLogado");
    if (usuarioLogado == null) {
        response.sendRedirect("acesso.jsp");
        return;
    }
    if (!"FUNCIONARIO".equalsIgnoreCase(usuarioLogado.getRole()) && !"GERENTE".equalsIgnoreCase(usuarioLogado.getRole())) {
        response.sendError(HttpServletResponse.SC_FORBIDDEN, "Acesso restrito para instrutores/funcionários.");
        return;
    }

    String nomeFunc = "";
    String cpfFunc = "";
    try (Connection connFunc = DbConnection.getConnection();
         PreparedStatement psFunc = connFunc.prepareStatement("SELECT nome, cpf FROM Funcionario WHERE idUsuario = ?")) {
        psFunc.setInt(1, usuarioLogado.getIdUsuario());
        try (ResultSet rsFunc = psFunc.executeQuery()) {
            if (rsFunc.next()) {
                nomeFunc = rsFunc.getString("nome");
                cpfFunc = rsFunc.getString("cpf");
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"pt-br\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Painel do Funcionário - Gestão de Treinos</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        .custom-card {\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            box-shadow: 0 4px 6px rgba(0,0,0,0.05);\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-light\">\n");
      out.write("\n");
      out.write("    <nav class=\"navbar navbar-dark bg-secondary mb-4\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <span class=\"navbar-brand mb-0 h1 fw-bold text-warning\">\n");
      out.write("                <i class=\"fas fa-dumbbell me-2\"></i> Painel do Instrutor\n");
      out.write("            </span>\n");
      out.write("            <div>\n");
      out.write("                <button class=\"btn btn-sm btn-outline-light me-2\" data-bs-toggle=\"modal\" data-bs-target=\"#modalPerfil\">\n");
      out.write("                    <i class=\"fas fa-user-cog me-1\"></i> Meus Dados\n");
      out.write("                </button>\n");
      out.write("                <span class=\"text-white small me-3\">Olá, ");
      out.print( nomeFunc.isEmpty() ? usuarioLogado.getEmailLogin() : nomeFunc );
      out.write("</span>\n");
      out.write("                <a href=\"api/logout\" class=\"btn btn-sm btn-danger\"><i class=\"fas fa-sign-out-alt me-1\"></i> Sair</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div class=\"container mb-5\">\n");
      out.write("        <div id=\"alert-funcionario\" class=\"alert d-none\" role=\"alert\"></div>\n");
      out.write("\n");
      out.write("        <div class=\"row g-4\">\n");
      out.write("            \n");
      out.write("            <!-- Atribuir / Trocar Treino do Aluno -->\n");
      out.write("            <div class=\"col-lg-6\">\n");
      out.write("                <div class=\"card custom-card p-4 h-100 bg-white\">\n");
      out.write("                    <h5 class=\"fw-bold text-dark mb-3\"><i class=\"fas fa-user-edit text-primary me-2\"></i> Atribuir / Trocar Treino do Aluno</h5>\n");
      out.write("                    <p class=\"text-muted small\">Selecione o aluno e marque quais blocos de treino ele deve realizar.</p>\n");
      out.write("                    \n");
      out.write("                    <form id=\"form-vincular-treino\">\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label for=\"select-aluno\" class=\"form-label fw-semibold\">Selecionar Aluno</label>\n");
      out.write("                            <select class=\"form-select\" id=\"select-aluno\" name=\"cpf_aluno\" required>\n");
      out.write("                                <option value=\"\" selected disabled>Escolha um aluno...</option>\n");
      out.write("                                ");

                                    Connection conn = null;
                                    PreparedStatement ps = null;
                                    ResultSet rs = null;
                                    try {
                                        conn = DbConnection.getConnection();
                                        String sql = "SELECT nome, cpf FROM Aluno ORDER BY nome ASC";
                                        ps = conn.prepareStatement(sql);
                                        rs = ps.executeQuery();
                                        while (rs.next()) {
                                            String nome = rs.getString("nome");
                                            String cpf = rs.getString("cpf");
                                
      out.write("\n");
      out.write("                                            <option value=\"");
      out.print( cpf );
      out.write('"');
      out.write('>');
      out.print( nome );
      out.write(" (CPF: ");
      out.print( cpf );
      out.write(")</option>\n");
      out.write("                                ");

                                        }
                                    } catch (Exception e) {
                                        e.printStackTrace();
                                    } finally {
                                        if (rs != null) try { rs.close(); } catch (Exception e) {}
                                        if (ps != null) try { ps.close(); } catch (Exception e) {}
                                        if (conn != null) try { conn.close(); } catch (Exception e) {}
                                    }
                                
      out.write("\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"mb-4\">\n");
      out.write("                            <label class=\"form-label fw-semibold d-block\">Selecione os Blocos Ativos</label>\n");
      out.write("                            <p class=\"text-muted card-text small mt-0 mb-2\">Os treinos selecionados serão vinculados diretamente ao perfil do aluno.</p>\n");
      out.write("                            \n");
      out.write("                            <div class=\"form-check form-check-inline\">\n");
      out.write("                                <input class=\"form-check-input chk-treino\" type=\"checkbox\" name=\"treinos\" id=\"chk-a\" value=\"A\">\n");
      out.write("                                <label class=\"form-check-label fw-medium\" for=\"chk-a\">Treino A</label>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"form-check form-check-inline\">\n");
      out.write("                                <input class=\"form-check-input chk-treino\" type=\"checkbox\" name=\"treinos\" id=\"chk-b\" value=\"B\">\n");
      out.write("                                <label class=\"form-check-label fw-medium\" for=\"chk-b\">Treino B</label>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"form-check form-check-inline\">\n");
      out.write("                                <input class=\"form-check-input chk-treino\" type=\"checkbox\" name=\"treinos\" id=\"chk-c\" value=\"C\">\n");
      out.write("                                <label class=\"form-check-label fw-medium\" for=\"chk-c\">Treino C</label>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"form-check form-check-inline\">\n");
      out.write("                                <input class=\"form-check-input chk-treino\" type=\"checkbox\" name=\"treinos\" id=\"chk-d\" value=\"D\">\n");
      out.write("                                <label class=\"form-check-label fw-medium\" for=\"chk-d\">Treino D</label>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <!-- Ficha de Treinos Atual do Aluno -->\n");
      out.write("                        <div id=\"ficha-atual-container\" class=\"mb-3 p-3 bg-light border rounded d-none\">\n");
      out.write("                            <h6 class=\"fw-bold text-dark mb-2 small\"><i class=\"fas fa-file-invoice text-secondary me-2\"></i> Ficha de Treinos Atual</h6>\n");
      out.write("                            <pre id=\"ficha-atual-texto\" class=\"mb-0 text-muted small\" style=\"white-space: pre-wrap; font-family: inherit; font-size: 0.85rem;\"></pre>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary w-100 fw-bold\" id=\"btn-salvar-aluno-treino\">\n");
      out.write("                            <span class=\"spinner-border spinner-border-sm d-none\" role=\"status\"></span>\n");
      out.write("                            Atualizar Ficha do Aluno\n");
      out.write("                        </button>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Criar / Editar Bloco de Treino -->\n");
      out.write("            <div class=\"col-lg-6\">\n");
      out.write("                <div class=\"card custom-card p-4 h-100 bg-white\">\n");
      out.write("                    <h5 class=\"fw-bold text-dark mb-3\"><i class=\"fas fa-folder-plus text-success me-2\"></i> Criar / Editar Bloco de Treino</h5>\n");
      out.write("                    <p class=\"text-muted small\">Monte a estrutura de exercícios de um bloco específico (ex: Bloco A, B, C...).</p>\n");
      out.write("                    \n");
      out.write("                    <form id=\"form-criar-treino\">\n");
      out.write("                        <div class=\"row g-2 mb-3\">\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"nome-bloco\" class=\"form-label fw-semibold\">Nome do Bloco</label>\n");
      out.write("                                <select class=\"form-select\" id=\"nome-bloco\" name=\"nome_bloco\" required>\n");
      out.write("                                    <option value=\"A\">Bloco A</option>\n");
      out.write("                                    <option value=\"B\">Bloco B</option>\n");
      out.write("                                    <option value=\"C\">Bloco C</option>\n");
      out.write("                                    <option value=\"D\">Bloco D</option>\n");
      out.write("                                </select>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"tipo-foco\" class=\"form-label fw-semibold\">Foco / Tipo</label>\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"tipo-foco\" name=\"tipo_foco\" placeholder=\"Ex: Peito e Tríceps\" required>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"mb-4\">\n");
      out.write("                            <label for=\"lista-exercicios\" class=\"form-label fw-semibold\">Exercícios do Bloco</label>\n");
      out.write("                            <p class=\"text-muted card-text small mt-0 mb-2\">Digite os exercícios separados por ponto e vírgula (;)</p>\n");
      out.write("                            <textarea class=\"form-control\" id=\"lista-exercicios\" name=\"exercicios\" rows=\"4\" \n");
      out.write("                                      placeholder=\"Supino Reto 4x10; Peck Deck 3x12; Tríceps Corda 4x12;\" required></textarea>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-success w-100 fw-bold\" id=\"btn-salvar-bloco\">\n");
      out.write("                            <span class=\"spinner-border spinner-border-sm d-none\" role=\"status\"></span>\n");
      out.write("                            Salvar Estrutura do Bloco\n");
      out.write("                        </button>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("    $(document).ready(function() {\n");
      out.write("        \n");
      out.write("        let alertBox = $('#alert-funcionario');\n");
      out.write("\n");
      out.write("        function exibirAlerta(mensagem, sucesso) {\n");
      out.write("            alertBox.removeClass('d-none alert-success alert-danger');\n");
      out.write("            if (sucesso) {\n");
      out.write("                alertBox.addClass('alert-success').text(mensagem);\n");
      out.write("            } else {\n");
      out.write("                alertBox.addClass('alert-danger').text(mensagem);\n");
      out.write("            }\n");
      out.write("            window.scrollTo({ top: 0, behavior: 'smooth' });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        // --- CARREGAR TREINOS E FICHA DO ALUNO AO SELECIONAR ---\n");
      out.write("        $('#select-aluno').on('change', function() {\n");
      out.write("            let cpfAluno = $(this).val();\n");
      out.write("            if (!cpfAluno) return;\n");
      out.write("\n");
      out.write("            // Limpa checkboxes e esconde a ficha anterior\n");
      out.write("            $('.chk-treino').prop('checked', false);\n");
      out.write("            $('#ficha-atual-container').addClass('d-none');\n");
      out.write("            $('#ficha-atual-texto').text('');\n");
      out.write("\n");
      out.write("            $.ajax({\n");
      out.write("                url: 'FuncionarioController',\n");
      out.write("                type: 'GET',\n");
      out.write("                data: {\n");
      out.write("                    acao: 'obterTreino',\n");
      out.write("                    cpf_aluno: cpfAluno\n");
      out.write("                },\n");
      out.write("                dataType: 'json',\n");
      out.write("                success: function(response) {\n");
      out.write("                    // Marcando os checkboxes corretos\n");
      out.write("                    if (response.blocosAtivos && Array.isArray(response.blocosAtivos)) {\n");
      out.write("                        response.blocosAtivos.forEach(function(bloco) {\n");
      out.write("                            $('.chk-treino[value=\"' + bloco + '\"]').prop('checked', true);\n");
      out.write("                        });\n");
      out.write("                    }\n");
      out.write("                    // Exibindo a ficha de treino atual\n");
      out.write("                    if (response.fichaTreino) {\n");
      out.write("                        $('#ficha-atual-texto').text(response.fichaTreino);\n");
      out.write("                        $('#ficha-atual-container').removeClass('d-none');\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                error: function() {\n");
      out.write("                    console.log('Erro ao buscar treinos ativos do aluno.');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        // --- VINCULAR OU TROCAR TREINO DO ALUNO ---\n");
      out.write("        $('#form-vincular-treino').on('submit', function(e) {\n");
      out.write("            e.preventDefault();\n");
      out.write("            \n");
      out.write("            let btn = $('#btn-salvar-aluno-treino');\n");
      out.write("            let spinner = btn.find('.spinner-border');\n");
      out.write("            \n");
      out.write("            btn.prop('disabled', true);\n");
      out.write("            spinner.removeClass('d-none');\n");
      out.write("\n");
      out.write("            let formData = $(this).serialize();\n");
      out.write("\n");
      out.write("            $.ajax({\n");
      out.write("                url: 'FuncionarioController',\n");
      out.write("                type: 'POST',\n");
      out.write("                data: formData + '&acao=vincularTreino',\n");
      out.write("                dataType: 'json',\n");
      out.write("                success: function(response) {\n");
      out.write("                    if (response.success) {\n");
      out.write("                        exibirAlerta(response.message || 'Ficha de treinos do aluno atualizada com sucesso!', true);\n");
      out.write("                        // Atualiza a ficha atual do aluno na tela\n");
      out.write("                        $('#select-aluno').trigger('change');\n");
      out.write("                    } else {\n");
      out.write("                        exibirAlerta(response.message || 'Erro ao atualizar treinos do aluno.', false);\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                error: function(xhr) {\n");
      out.write("                    let msg = 'Erro técnico de comunicação ao salvar a ficha do aluno.';\n");
      out.write("                    if (xhr.responseJSON && xhr.responseJSON.message) {\n");
      out.write("                        msg = xhr.responseJSON.message;\n");
      out.write("                    }\n");
      out.write("                    exibirAlerta(msg, false);\n");
      out.write("                },\n");
      out.write("                complete: function() {\n");
      out.write("                    btn.prop('disabled', false);\n");
      out.write("                    spinner.addClass('d-none');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        // --- CRIAR OU EDITAR UM BLOCO DE TREINO ---\n");
      out.write("        $('#form-criar-treino').on('submit', function(e) {\n");
      out.write("            e.preventDefault();\n");
      out.write("            \n");
      out.write("            let btn = $('#btn-salvar-bloco');\n");
      out.write("            let spinner = btn.find('.spinner-border');\n");
      out.write("            \n");
      out.write("            btn.prop('disabled', true);\n");
      out.write("            spinner.removeClass('d-none');\n");
      out.write("\n");
      out.write("            let formData = $(this).serialize();\n");
      out.write("\n");
      out.write("            $.ajax({\n");
      out.write("                url: 'FuncionarioController',\n");
      out.write("                type: 'POST',\n");
      out.write("                data: formData + '&acao=criarBloco',\n");
      out.write("                dataType: 'json',\n");
      out.write("                success: function(response) {\n");
      out.write("                    if (response.success) {\n");
      out.write("                        exibirAlerta(response.message || 'Estrutura do Bloco salva com sucesso no banco!', true);\n");
      out.write("                        $('#form-criar-treino')[0].reset();\n");
      out.write("                    } else {\n");
      out.write("                        exibirAlerta(response.message || 'Erro ao salvar o bloco de treino.', false);\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                error: function(xhr) {\n");
      out.write("                    let msg = 'Erro técnico de comunicação ao salvar o bloco.';\n");
      out.write("                    if (xhr.responseJSON && xhr.responseJSON.message) {\n");
      out.write("                        msg = xhr.responseJSON.message;\n");
      out.write("                    }\n");
      out.write("                    exibirAlerta(msg, false);\n");
      out.write("                },\n");
      out.write("                complete: function() {\n");
      out.write("                    btn.prop('disabled', false);\n");
      out.write("                    spinner.addClass('d-none');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("        // --- AJAX: ATUALIZAR PERFIL DO FUNCIONÁRIO ---\n");
      out.write("        $('#form-perfil').on('submit', function(e) {\n");
      out.write("            e.preventDefault();\n");
      out.write("            \n");
      out.write("            let btn = $('#btn-salvar-perfil');\n");
      out.write("            let spinner = btn.find('.spinner-border');\n");
      out.write("            let alertBox = $('#perfil-alert');\n");
      out.write("\n");
      out.write("            alertBox.addClass('d-none').removeClass('alert-success alert-danger');\n");
      out.write("            btn.prop('disabled', true);\n");
      out.write("            spinner.removeClass('d-none');\n");
      out.write("\n");
      out.write("            let formData = {\n");
      out.write("                nome: $('#perf-nome').val(),\n");
      out.write("                email: $('#perf-email').val()\n");
      out.write("            };\n");
      out.write("\n");
      out.write("            $.ajax({\n");
      out.write("                url: 'api/atualizar-perfil',\n");
      out.write("                type: 'POST',\n");
      out.write("                contentType: 'application/json',\n");
      out.write("                data: JSON.stringify(formData),\n");
      out.write("                dataType: 'json',\n");
      out.write("                success: function(response) {\n");
      out.write("                    if (response.sucesso) {\n");
      out.write("                        alertBox.removeClass('d-none').addClass('alert-success').text(response.mensagem);\n");
      out.write("                        setTimeout(function() {\n");
      out.write("                            location.reload();\n");
      out.write("                        }, 1200);\n");
      out.write("                    } else {\n");
      out.write("                        alertBox.removeClass('d-none').addClass('alert-danger').text(response.mensagem || 'Erro ao atualizar dados.');\n");
      out.write("                        btn.prop('disabled', false);\n");
      out.write("                        spinner.addClass('d-none');\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                error: function(xhr) {\n");
      out.write("                    let msg = 'Erro ao processar alteração de perfil.';\n");
      out.write("                    if (xhr.responseJSON && xhr.responseJSON.mensagem) {\n");
      out.write("                        msg = xhr.responseJSON.mensagem;\n");
      out.write("                    }\n");
      out.write("                    alertBox.removeClass('d-none').addClass('alert-danger').text(msg);\n");
      out.write("                    btn.prop('disabled', false);\n");
      out.write("                    spinner.addClass('d-none');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("    <!-- Modal Perfil Funcionário -->\n");
      out.write("    <div class=\"modal fade\" id=\"modalPerfil\" tabindex=\"-1\" aria-labelledby=\"modalPerfilLabel\" aria-hidden=\"true\">\n");
      out.write("        <div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("                    <h5 class=\"modal-title fw-bold\" id=\"modalPerfilLabel\"><i class=\"fas fa-user-cog me-2\"></i> Meus Dados</h5>\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Fechar\"></button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-body\">\n");
      out.write("                    <div id=\"perfil-alert\" class=\"alert d-none\" role=\"alert\"></div>\n");
      out.write("                    <form id=\"form-perfil\">\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label for=\"perf-nome\" class=\"form-label fw-semibold\">Nome Completo</label>\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"perf-nome\" required value=\"");
      out.print( nomeFunc );
      out.write("\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label for=\"perf-cpf\" class=\"form-label fw-semibold\">CPF (não alterável)</label>\n");
      out.write("                            <input type=\"text\" class=\"form-control bg-light\" id=\"perf-cpf\" value=\"");
      out.print( cpfFunc );
      out.write("\" readonly>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label for=\"perf-email\" class=\"form-label fw-semibold\">E-mail</label>\n");
      out.write("                            <input type=\"email\" class=\"form-control\" id=\"perf-email\" required value=\"");
      out.print( usuarioLogado.getEmailLogin() );
      out.write("\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"d-grid mt-4\">\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-primary\" id=\"btn-salvar-perfil\">\n");
      out.write("                                <span class=\"spinner-border spinner-border-sm d-none\" role=\"status\" aria-hidden=\"true\"></span>\n");
      out.write("                                Salvar Alterações\n");
      out.write("                            </button>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
